### ISSUE TITLE
#3 find the positive quotes related to female in tech

### ISSUE THREAD

**Issue by Ayselin** [kodiri/8-days-a-week#4]
10 quotes pls

**Comment by alwyn3540** [comment]
https://twitter.com/dimensionmedia/status/1090972975686250496
https://www.gadgette.com/2016/03/29/women-in-tech-history-eniac-and-the-programming-pioneers-that-nobody-knew/
https://twitter.com/TaelurAlexis
https://twitter.com/OneDevloperArmy/status/1028964083813560320
